name: api-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: be-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: env 파일 생성
        run: |
          cd ~/code-sync-be/
          rm .env
          touch .env
          echo DATABASE_HOSTNAME=${{ secrets.DATABASE_HOSTNAME }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo JWT_EXPIRES=${{ secrets.JWT_EXPIRES }} >> .env
          echo COOKIE_AGE=${{ secrets.COOKIE_AGE }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_REGION=${{ secrets.AWS_REGION }} >> .env
          echo AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} >> .env
          cat .env

      - name: run deploy
        run: |
          /bin/bash ~/deploy.sh
