name: api-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: be-dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: path 변경
        run: |
          cd ~/code-sync-be/

      - name: env 파일 생성
        run: |
          touch .env
          echo DATABASE_HOSTNAME=${{ secrets.DATABASE_HOSTNAME }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo DATABASE=${{ secrets.DATABASE }} >> .env
          echo DATABASE_USER=${{ secrets.DATABASE_USER }} >> .env
          echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
          echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo JWT_EXPIRES=${{ secrets.JWT_EXPIRES }} >> .env
          echo COOKIE_AGE=${{ secrets.COOKIE_AGE }} >> .env
          cat .env

      - name: run deply
        run: |
          sh ~/deploy.sh
